// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKSkgtnjJjKaH1PyuDbY5uoYlyU0A3IXU',
    appId: '1:174127201324:web:d9afdc3c681cc3ff886589',
    messagingSenderId: '174127201324',
    projectId: 'aasaantransit-39662',
    authDomain: 'aasaantransit-39662.firebaseapp.com',
    storageBucket: 'aasaantransit-39662.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSKRhXGSuFCE5cqw6tbhLtLtDfgYZPzgo',
    appId: '1:174127201324:android:3fed16b98a3070f5886589',
    messagingSenderId: '174127201324',
    projectId: 'aasaantransit-39662',
    storageBucket: 'aasaantransit-39662.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQtSr3GR2FDCOD-JW4dWakTDKGpTmOqR8',
    appId: '1:174127201324:ios:cd8fdf0d2627f9e3886589',
    messagingSenderId: '174127201324',
    projectId: 'aasaantransit-39662',
    storageBucket: 'aasaantransit-39662.firebasestorage.app',
    iosBundleId: 'com.example.aasaanTransit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQtSr3GR2FDCOD-JW4dWakTDKGpTmOqR8',
    appId: '1:174127201324:ios:cd8fdf0d2627f9e3886589',
    messagingSenderId: '174127201324',
    projectId: 'aasaantransit-39662',
    storageBucket: 'aasaantransit-39662.firebasestorage.app',
    iosBundleId: 'com.example.aasaanTransit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKSkgtnjJjKaH1PyuDbY5uoYlyU0A3IXU',
    appId: '1:174127201324:web:eca73bb4c7ee85cb886589',
    messagingSenderId: '174127201324',
    projectId: 'aasaantransit-39662',
    authDomain: 'aasaantransit-39662.firebaseapp.com',
    storageBucket: 'aasaantransit-39662.firebasestorage.app',
  );
}
